const blocks = [
  { name: "stone-white" },
  { name: "stone-lightgray" },
  { name: "stone-darkgray" },
  { name: "stone-black" },
  { name: "stone-red" },
  { name: "stone-lightred" },
  { name: "stone-darkred" },
  { name: "stone-green" },
  { name: "stone-lightgreen" },
  { name: "stone-darkgreen" },
  { name: "stone-blue" },
  { name: "stone-lightblue" },
  { name: "stone-darkblue" },
  { name: "stone-pink" },
  { name: "stone-purple" },
  { name: "stone-yellow" },
  { name: "stone-orange" },
  { name: "stone-brown" },
  { name: "stone-lightbrown" },
  { name: "stone-darkbrown" },
  { name: "glow-white" },
  { name: "glow-yellow" },
  { name: "glow-red" },
  { name: "glow-magenta" },
  { name: "glow-cyan" },
  { name: "glow-green" },
  { name: "column-white" },
  { name: "fence" },
  { name: "half-white" },
  { name: "shelf" },
  { name: "oven" },
  { name: "table" },
  { name: "chair" },
  { name: "cupboard" },
]

export default blocks
