const blocks = [
  { name: "stone-white", groups: ["resource"] },
  { name: "stone-lightgray", groups: ["resource"] },
  { name: "stone-darkgray", groups: ["resource", "stone"] },
  { name: "stone-black", groups: ["resource", "stone"] },
  { name: "stone-red", groups: ["resource"] },
  { name: "stone-lightred", groups: ["resource"] },
  { name: "stone-darkred", groups: ["resource", "stone"] },
  { name: "stone-green", groups: ["resource"] },
  { name: "stone-lightgreen", groups: ["resource"] },
  { name: "stone-darkgreen", groups: ["resource"] },
  { name: "stone-blue", groups: ["water"] },
  { name: "stone-lightblue", groups: ["water"] },
  { name: "stone-darkblue", groups: ["resource"] },
  { name: "stone-pink", groups: ["resource"] },
  { name: "stone-purple", groups: ["resource"] },
  { name: "stone-yellow", groups: ["resource"] },
  { name: "stone-orange", groups: ["resource"] },
  { name: "stone-brown", groups: ["resource"] },
  { name: "stone-lightbrown", groups: ["resource"] },
  { name: "stone-darkbrown", groups: ["resource", "stone"] },
  { name: "glow-white", groups: ["light"] },
  { name: "glow-yellow", groups: ["resource"] },
  { name: "glow-red", groups: ["resource"] },
  { name: "glow-magenta", groups: ["resource"] },
  { name: "glow-cyan", groups: ["resource"] },
  { name: "glow-green", groups: ["resource"] },
  { name: "column-white", groups: ["processed"] },
  { name: "fence", groups: ["processed"] },
  { name: "shelf", groups: ["processed", "furniture"] },
  { name: "oven", groups: ["processed", "furniture"] },
  { name: "table", groups: ["processed", "furniture"] },
  { name: "chair", groups: ["processed", "furniture"] },
  { name: "cupboard", groups: ["processed", "furniture"] },
]

export default blocks
